### PR TITLE
allows for file-like uploads

### PR DESCRIPTION
**Pull request by cmhedrick**
I was working on a project and needed to be able to upload InMemoryUploadedFile objects to vimeo.

### CODE REVIEW

**Comment by Dashron** [comment]
This is great. Can you start by submitting it through our CLA (developer.vimeo.com/cla, pardon the design issues I'm getting those fixed now).

@greedo when you have some time look over the code, and test it out.

**Comment by cmhedrick** [comment]
Sorry it took so long to submit it through the CLA. Been busy lately, but now its submitted! However I did make one typo in the message. ><

**Comment by Dashron** [comment]
No worries! I'll get someone in to test this, and then we can make the merge.

**Comment by agilefox** [comment]
Looks good to me. Works and adds something. Sorry it took so long to get it merged!

**Pull request merged**
