### PR TITLE
Drop support for EOL Python 2.7

### LINKED ISSUE #140: Drop support for Python 2
We've been getting a number of support cases over the past few months for upgrading tuspy to the latest version (https://github.com/vimeo/vimeo.py/pull/136). Unfortunately we can't do that because support for Python 2 was dropped in version 0.2.2.

Let's drop our support for Python 2 as well, upgrade tus, and release a 2.0 release. Let's also branch off the current master so we can retain the ability to do support releases for the 1.x release branch if need be.

### PR DESCRIPTION
**Pull request by hugovk**
Fixes https://github.com/vimeo/vimeo.py/issues/140. 

Example CI build: https://travis-ci.org/hugovk/vimeo.py/builds/566365592

### CODE REVIEW

**Comment by hugovk** [comment]
I've signed the CLA, https://cla-assistant.io/vimeo/vimeo.py?pullRequest=147 shows me:

image

**Review by amrutadotorg — APPROVED** [review]
Hi, I can confirm that everything works as expected. I was able to successfully upload 18 videos (ranging between 20M-1200M in size) via Python 3.6.8. I also successfully used v.get, v.patch and v.put methods. 

Great work!

**Comment by hugovk** [comment]
Thank you for testing!

**Comment by jaylinski** [comment]
@danimality @amrutadotorg I don't know if you have rights to merge PRs on this repo, but if you have: can we please get this merged? :open_hands: 

https://pythonclock.org/

**Comment by hugovk** [comment]
Title updated :) 

Happy new year!

**Review by radoslawoska — APPROVED** [review]
Tested with Python 3.7.3, successfully uploaded 9 videos (15-300MB)

$python3 -m venv V3

$git clone https://github.com/vimeo/vimeo.py.git

Cloning into 'vimeo.py'...
remote: Enumerating objects: 782, done.
remote: Total 782 (delta 0), reused 0 (delta 0), pack-reused 782
Receiving objects: 100% (782/782), 170.50 KiB | 0 bytes/s, done.
Resolving deltas: 100% (449/449), done.

$cd vimeo.py/

$git fetch origin  pull/147/head:pull_147
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 34 (delta 24), reused 34 (delta 24), pack-reused 0
Unpacking objects: 100% (34/34), done.
From https://github.com/vimeo/vimeo.py
 * [new ref]         refs/pull/147/head -> pull_147

$git checkout pull_147

Switched to branch 'pull_147'

$python3 setup.py install

running install
running bdist_egg
running egg_info
creating PyVimeo.egg-info
writing PyVimeo.egg-info/PKG-INFO
writing dependency_links to PyVimeo.egg-info/dependency_links.txt
writing requirements to PyVimeo.egg-info/requires.txt
writing top-level names to PyVimeo.egg-info/top_level.txt
writing manifest file 'PyVimeo.egg-info/SOURCES.txt'
reading manifest file 'PyVimeo.egg-info/SOURCES.txt'
writing manifest file 'PyVimeo.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/vimeo
copying vimeo/upload.py -> build/lib/vimeo
copying vimeo/exceptions.py -> build/lib/vimeo
copying vimeo/__init__.py -> build/lib/vimeo
copying vimeo/client.py -> build/lib/vimeo
creating build/lib/vimeo/auth
copying vimeo/auth/client_credentials.py -> build/lib/vimeo/auth
copying vimeo/auth/base.py -> build/lib/vimeo/auth
copying vimeo/auth/__init__.py -> build/lib/vimeo/auth
copying vimeo/auth/authorization_code.py -> build/lib/vimeo/auth
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/vimeo
creating build/bdist.linux-x86_64/egg/vimeo/auth
copying build/lib/vimeo/auth/client_credentials.py -> build/bdist.linux-x86_64/egg/vimeo/auth
copying build/lib/vimeo/auth/base.py -> build/bdist.linux-x86_64/egg/vimeo/auth
copying build/lib/vimeo/auth/__init__.py -> build/bdist.linux-x86_64/egg/vimeo/auth
copying build/lib/vimeo/auth/authorization_code.py -> build/bdist.linux-x86_64/egg/vimeo/auth
copying build/lib/vimeo/upload.py -> build/bdist.linux-x86_64/egg/vimeo
copying build/lib/vimeo/exceptions.py -> build/bdist.linux-x86_64/egg/vimeo
copying build/lib/vimeo/__init__.py -> build/bdist.linux-x86_64/egg/vimeo
copying build/lib/vimeo/client.py -> build/bdist.linux-x86_64/egg/vimeo
byte-compiling build/bdist.linux-x86_64/egg/vimeo/auth/client_credentials.py to client_credentials.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/vimeo/auth/base.py to base.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/vimeo/auth/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/vimeo/auth/authorization_code.py to authorization_code.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/vimeo/upload.py to upload.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/vimeo/exceptions.py to exceptions.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/vimeo/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/vimeo/client.py to client.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying PyVimeo.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyVimeo.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyVimeo.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyVimeo.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyVimeo.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/PyVimeo-1.0.11-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing PyVimeo-1.0.11-py3.7.egg
Copying PyVimeo-1.0.11-py3.7.egg to /home/xxx/py/V3/lib/python3.7/site-packages
Adding PyVimeo 1.0.11 to easy-install.pth file

Installed /home/xxx/py/V3/lib/python3.7/site-packages/PyVimeo-1.0.11-py3.7.egg
Processing dependencies for PyVimeo==1.0.11
Searching for tuspy>=0.2.1
Reading https://pypi.org/simple/tuspy/
Downloading https://files.pythonhosted.org/packages/68/9c/21dedeb7e98a1d905a529a1ba044482510e5954bb70bd4392984e44b5785/tuspy-0.2.4.tar.gz#sha256=49b674003bbdb0e2ee3fc949490f85ca381929f712f17a7a56404ff6217e96e8
Best match: tuspy 0.2.4
Processing tuspy-0.2.4.tar.gz
Writing /tmp/easy_install-k663xeix/tuspy-0.2.4/setup.cfg
Running tuspy-0.2.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-k663xeix/tuspy-0.2.4/egg-dist-tmp-kqsrsbsi
zip_safe flag not set; analyzing archive contents...
Moving tuspy-0.2.4-py3.7.egg to /home/xxx/py/V3/lib/python3.7/site-packages
Adding tuspy 0.2.4 to easy-install.pth file

Installed /home/xxx/py/V3/lib/python3.7/site-packages/tuspy-0.2.4-py3.7.egg
Searching for requests>=2.4.0
Reading https://pypi.org/simple/requests/
Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl#sha256=9cf5292fcd0f598c671cfc1e0d7d1a7f13bb8085e9a590f48c010551dc6c4b31
Best match: requests 2.22.0
Processing requests-2.22.0-py2.py3-none-any.whl
Installing requests-2.22.0-py2.py3-none-any.whl to /home/xxx/py/V3/lib/python3.7/site-packages
writing requirements to /home/xxx/py/V3/lib/python3.7/site-packages/requests-2.22.0-py3.7.egg/EGG-INFO/requires.txt
Adding requests 2.22.0 to easy-install.pth file

Installed /home/xxx/py/V3/lib/python3.7/site-packages/requests-2.22.0-py3.7.egg
Searching for certifi>=2018.1.18
Reading https://pypi.org/simple/certifi/
Downloading https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl#sha256=017c25db2a153ce562900032d5bc68e9f191e44e9a0f762f373977de9df1fbb3
Best match: certifi 2019.11.28
Processing certifi-2019.11.28-py2.py3-none-any.whl
Installing certifi-2019.11.28-py2.py3-none-any.whl to /home/xxx/py/V3/lib/python3.7/site-packages
Adding certifi 2019.11.28 to easy-install.pth file

Installed /home/xxx/py/V3/lib/python3.7/site-packages/certifi-2019.11.28-py3.7.egg
Searching for tinydb>=3.5.0
Reading https://pypi.org/simple/tinydb/
Downloading https://files.pythonhosted.org/packages/22/11/c3adfc1b367d1955461f82a4a0a8ffffd37b193e98f2fe89338cdd4a8a6a/tinydb-3.15.2-py2.py3-none-any.whl#sha256=1087ade5300c47dbf9539d9f6dafd53115bd5e85a67d480d8188bdbfa2d9eaf4
Best match: tinydb 3.15.2
Processing tinydb-3.15.2-py2.py3-none-any.whl
Installing tinydb-3.15.2-py2.py3-none-any.whl to /home/xxx/py/V3/lib/python3.7/site-packages
Adding tinydb 3.15.2 to easy-install.pth file

Installed /home/xxx/py/V3/lib/python3.7/site-packages/tinydb-3.15.2-py3.7.egg
Searching for six>=1.11.0
Reading https://pypi.org/simple/six/
Downloading https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl#sha256=1f1b7d42e254082a9db6279deae68afb421ceba6158efa6131de7b3003ee93fd
Best match: six 1.13.0
Processing six-1.13.0-py2.py3-none-any.whl
Installing six-1.13.0-py2.py3-none-any.whl to /home/xxx/py/V3/lib/python3.7/site-packages
Adding six 1.13.0 to easy-install.pth file

Installed /home/xxx/py/V3/lib/python3.7/site-packages/six-1.13.0-py3.7.egg
Searching for future>=0.16.0
Reading https://pypi.org/simple/future/
Downloading https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz#sha256=b1bead90b70cf6ec3f0710ae53a525360fa360d306a86583adc6bf83a4db537d
Best match: future 0.18.2
Processing future-0.18.2.tar.gz
Writing /tmp/easy_install-r5kpejg0/future-0.18.2/setup.cfg
Running future-0.18.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-r5kpejg0/future-0.18.2/egg-dist-tmp-5vl5h1px
warning: no files found matching '*.au' under directory 'tests'
warning: no files found matching '*.gif' under directory 'tests'
warning: no files found matching '*.txt' under directory 'tests'
zip_safe flag not set; analyzing archive contents...
future.backports.test.__pycache__.ssl_servers.cpython-37: module references __file__
future.backports.test.__pycache__.support.cpython-37: module references __file__
future.standard_library.__pycache__.__init__.cpython-37: module references __file__
future.standard_library.__pycache__.__init__.cpython-37: module references __path__
future.utils.__pycache__.__init__.cpython-37: module MAY be using inspect.stack
past.builtins.__pycache__.misc.cpython-37: module MAY be using inspect.stack
past.translation.__pycache__.__init__.cpython-37: module references __file__
past.translation.__pycache__.__init__.cpython-37: module references __path__
creating /home/xxx/py/V3/lib/python3.7/site-packages/future-0.18.2-py3.7.egg
Extracting future-0.18.2-py3.7.egg to /home/xxx/py/V3/lib/python3.7/site-packages
Adding future 0.18.2 to easy-install.pth file
Installing futurize script to /home/xxx/py/V3/bin
Installing pasteurize script to /home/xxx/py/V3/bin

Installed /home/xxx/py/V3/lib/python3.7/site-packages/future-0.18.2-py3.7.egg
Searching for urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
Reading https://pypi.org/simple/urllib3/
Downloading https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl#sha256=a8a318824cc77d1fd4b2bec2ded92646630d7fe8619497b142c84a9e6f5a7293
Best match: urllib3 1.25.7
Processing urllib3-1.25.7-py2.py3-none-any.whl
Installing urllib3-1.25.7-py2.py3-none-any.whl to /home/xxx/py/V3/lib/python3.7/site-packages
writing requirements to /home/xxx/py/V3/lib/python3.7/site-packages/urllib3-1.25.7-py3.7.egg/EGG-INFO/requires.txt
Adding urllib3 1.25.7 to easy-install.pth file

Installed /home/xxx/py/V3/lib/python3.7/site-packages/urllib3-1.25.7-py3.7.egg
Searching for idna<2.9,>=2.5
Reading https://pypi.org/simple/idna/
Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl#sha256=ea8b7f6188e6fa117537c3df7da9fc686d485087abf6ac197f9c46432f7e4a3c
Best match: idna 2.8
Processing idna-2.8-py2.py3-none-any.whl
Installing idna-2.8-py2.py3-none-any.whl to /home/xxx/py/V3/lib/python3.7/site-packages
Adding idna 2.8 to easy-install.pth file

Installed /home/xxx/py/V3/lib/python3.7/site-packages/idna-2.8-py3.7.egg
Searching for chardet<3.1.0,>=3.0.2
Reading https://pypi.org/simple/chardet/
Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl#sha256=fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691
Best match: chardet 3.0.4
Processing chardet-3.0.4-py2.py3-none-any.whl
Installing chardet-3.0.4-py2.py3-none-any.whl to /home/xxx/py/V3/lib/python3.7/site-packages
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /home/xxx/py/V3/bin

Installed /home/xxx/py/V3/lib/python3.7/site-packages/chardet-3.0.4-py3.7.egg
Finished processing dependencies for PyVimeo==1.0.11

**Comment by GeyseR** [comment]
We use vimeo.py for checking duration for Vimeo videos and this version works perfectly for us.
LTGM

**Review by muglug — APPROVED** [review]

**Comment by muglug** [comment]
Thanks!

**Pull request merged**
